apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-microservice
  namespace: big-data-course-451012
spec:
  template:
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/big-data-course-451012/ai-microservice/ai-microservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_API_KEY
                  key: latest
