import 'package:sarasvant/models/assignments.dart';

final List<Assignments> dummyAssignments = [
  Assignments(
    id: '201',
    title: 'Math Assignment 1',
    body: 'Complete all exercises from Chapter 2.',
    attachments: ['attachment1.pdf', 'attachment2.png'],
    dueDate: DateTime(2024, 11, 15),
    createdAt: DateTime(2024, 11, 1),
    points: 50,
    commentIds: ['301', '302'],
  ),
  Assignments(
    id: '202',
    title: 'Science Project',
    body: 'Prepare a model of the solar system.',
    attachments: ['model_guidelines.pdf', 'reference_image.jpg'],
    dueDate: DateTime(2024, 11, 20),
    createdAt: DateTime(2024, 11, 5),
    points: 100,
    commentIds: ['303', '304'],
  ),
  Assignments(
    id: '203',
    title: 'History Essay',
    body: 'Write an essay on the French Revolution.',
    attachments: ['essay_template.docx'],
    dueDate: DateTime(2024, 11, 25),
    createdAt: DateTime(2024, 11, 10),
    points: 30,
    commentIds: ['305', '306'],
  ),
  Assignments(
    id: '204',
    title: 'English Literature',
    body: 'Read "Romeo and Juliet" and answer the questions.',
    attachments: ['questionnaire.pdf'],
    dueDate: DateTime(2024, 11, 22),
    createdAt: DateTime(2024, 11, 8),
    points: 40,
    commentIds: ['307', '308'],
  ),
  Assignments(
    id: '205',
    title: 'Computer Science Quiz',
    body: 'Complete the online quiz on data structures.',
    attachments: [],
    dueDate: DateTime(2024, 11, 18),
    createdAt: DateTime(2024, 11, 3),
    points: 20,
    commentIds: ['309', '310'],
  ),
];
