import 'package:sarasvant/models/questions.dart';
import 'package:sarasvant/models/variable.dart';

final List<Question> dummyQuestions = [
  Question(
    id: 'Q1',
    bankId: 'P1',
    question: 'What is the capital of France?',
    tags: ['geography', 'capital', 'MCQ'],
    variable: [
      Variable(
        id: 'V1',
        name: 'Paris',
        namePosition: {'en': (0, 5)},
        valuePosition: {'en': (6, 11)},
        unit: '',
        unitPosition: {'en': (12, 12)},
        variableType: 'string',
      ),
      Variable(
        id: 'V2',
        name: 'Berlin',
        namePosition: {'en': (0, 6)},
        valuePosition: {'en': (7, 13)},
        unit: '',
        unitPosition: {'en': (14, 14)},
        variableType: 'string',
      ),
    ],
    points: 10,
  ),
  Question(
    id: 'Q2',
    bankId: 'P2',
    question: 'Solve: 5 + 3',
    tags: ['math', 'addition', 'MCQ'],
    variable: [
      Variable(
        id: 'V3',
        name: '8',
        namePosition: {'en': (0, 1)},
        valuePosition: {'en': (2, 3)},
        unit: '',
        unitPosition: {'en': (4, 4)},
        variableType: 'int',
      ),
      Variable(
        id: 'V4',
        name: '9',
        namePosition: {'en': (0, 1)},
        valuePosition: {'en': (2, 3)},
        unit: '',
        unitPosition: {'en': (4, 4)},
        variableType: 'int',
      ),
    ],
    points: 5,
  ),
  Question(
    id: 'Q3',
    bankId: 'P1',
    question: 'What is the chemical symbol for water?',
    tags: ['chemistry', 'water', 'MCQ'],
    variable: [
      Variable(
        id: 'V5',
        name: 'H2O',
        namePosition: {'en': (0, 3)},
        valuePosition: {'en': (4, 7)},
        unit: '',
        unitPosition: {'en': (8, 8)},
        variableType: 'string',
      ),
      Variable(
        id: 'V6',
        name: 'CO2',
        namePosition: {'en': (0, 3)},
        valuePosition: {'en': (4, 7)},
        unit: '',
        unitPosition: {'en': (8, 8)},
        variableType: 'string',
      ),
    ],
    points: 8,
  ),
  Question(
    id: 'Q4',
    bankId: 'P3',
    question: 'Who wrote "Romeo and Juliet"?',
    tags: ['literature', 'author', 'MCQ'],
    variable: [
      Variable(
        id: 'V7',
        name: 'William Shakespeare',
        namePosition: {'en': (0, 18)},
        valuePosition: {'en': (19, 37)},
        unit: '',
        unitPosition: {'en': (38, 38)},
        variableType: 'string',
      ),
      Variable(
        id: 'V8',
        name: 'Charles Dickens',
        namePosition: {'en': (0, 15)},
        valuePosition: {'en': (16, 31)},
        unit: '',
        unitPosition: {'en': (32, 32)},
        variableType: 'string',
      ),
    ],
    points: 12,
  ),
  Question(
    id: 'Q5',
    bankId: 'P2',
    question: 'What is 10 * 10?',
    tags: ['math', 'multiplication', 'MCQ'],
    variable: [
      Variable(
        id: 'V9',
        name: '100',
        namePosition: {'en': (0, 3)},
        valuePosition: {'en': (4, 7)},
        unit: '',
        unitPosition: {'en': (8, 8)},
        variableType: 'int',
      ),
      Variable(
        id: 'V10',
        name: '101',
        namePosition: {'en': (0, 3)},
        valuePosition: {'en': (4, 7)},
        unit: '',
        unitPosition: {'en': (8, 8)},
        variableType: 'int',
      ),
    ],
    points: 7,
  ),
];