import '../../../models/questions/mcq.dart';
import '../../../models/variable.dart';

final List<MCQ> dummyMCQs = [
  MCQ(
    id: 'mcq_1',
    bankId: '101',
    question: 'What is the acceleration of an object when a force of 20N is applied to a mass of 5kg?',
    variable: [
      Variable(
        id: 'var_1',
        name: 'Force',
        namePosition: {'start': (0, 0), 'end': (0, 5)},
        valuePosition: {'start': (0, 7), 'end': (0, 9)},
        unit: 'N',
        unitPosition: {'start': (0, 10), 'end': (0, 11)},
        variableType: 'scalar',
      ),
      Variable(
        id: 'var_2',
        name: 'Mass',
        namePosition: {'start': (1, 0), 'end': (1, 4)},
        valuePosition: {'start': (1, 6), 'end': (1, 7)},
        unit: 'kg',
        unitPosition: {'start': (1, 8), 'end': (1, 10)},
        variableType: 'scalar',
      ),
    ],
    points: 5,
    options: ['2 m/s²', '4 m/s²', '5 m/s²', '10 m/s²'],
    answer: '4 m/s²',
  ),
  MCQ(
    id: 'mcq_2',
    bankId: '102',
    question: 'What is the frequency of a wave with a speed of 300 m/s and a wavelength of 5 m?',
    variable: [
      Variable(
        id: 'var_3',
        name: 'Speed',
        namePosition: {'start': (0, 0), 'end': (0, 5)},
        valuePosition: {'start': (0, 7), 'end': (0, 10)},
        unit: 'm/s',
        unitPosition: {'start': (0, 11), 'end': (0, 14)},
        variableType: 'scalar',
      ),
      Variable(
        id: 'var_4',
        name: 'Wavelength',
        namePosition: {'start': (1, 0), 'end': (1, 9)},
        valuePosition: {'start': (1, 11), 'end': (1, 12)},
        unit: 'm',
        unitPosition: {'start': (1, 13), 'end': (1, 14)},
        variableType: 'scalar',
      ),
    ],
    points: 5,
    options: ['10 Hz', '50 Hz', '60 Hz', '75 Hz'],
    answer: '60 Hz',
  ),
  MCQ(
    id: 'mcq_3',
    bankId: '103',
    question: 'Calculate the area of a rectangle with length 10m and width 5m.',
    variable: [
      Variable(
        id: 'var_5',
        name: 'Length',
        namePosition: {'start': (0, 0), 'end': (0, 6)},
        valuePosition: {'start': (0, 8), 'end': (0, 10)},
        unit: 'm',
        unitPosition: {'start': (0, 11), 'end': (0, 12)},
        variableType: 'scalar',
      ),
      Variable(
        id: 'var_6',
        name: 'Width',
        namePosition: {'start': (1, 0), 'end': (1, 5)},
        valuePosition: {'start': (1, 7), 'end': (1, 8)},
        unit: 'm',
        unitPosition: {'start': (1, 9), 'end': (1, 10)},
        variableType: 'scalar',
      ),
    ],
    points: 5,
    options: ['50 m²', '100 m²', '200 m²', '300 m²'],
    answer: '50 m²',
  ),
  MCQ(
    id: 'mcq_4',
    bankId: '104',
    question: 'What is the potential energy of a 10kg object lifted to a height of 5m? (g = 9.8 m/s²)',
    variable: [
      Variable(
        id: 'var_7',
        name: 'Mass',
        namePosition: {'start': (0, 0), 'end': (0, 4)},
        valuePosition: {'start': (0, 6), 'end': (0, 8)},
        unit: 'kg',
        unitPosition: {'start': (0, 9), 'end': (0, 11)},
        variableType: 'scalar',
      ),
      Variable(
        id: 'var_8',
        name: 'Height',
        namePosition: {'start': (1, 0), 'end': (1, 6)},
        valuePosition: {'start': (1, 8), 'end': (1, 9)},
        unit: 'm',
        unitPosition: {'start': (1, 10), 'end': (1, 11)},
        variableType: 'scalar',
      ),
    ],
    points: 6,
    options: ['490 J', '980 J', '1960 J', '2940 J'],
    answer: '490 J',
  ),
  MCQ(
    id: 'mcq_5',
    bankId: '105',
    question: 'What is the volume of a cylinder with radius 2m and height 10m? (Use π = 3.14)',
    variable: [
      Variable(
        id: 'var_9',
        name: 'Radius',
        namePosition: {'start': (0, 0), 'end': (0, 6)},
        valuePosition: {'start': (0, 8), 'end': (0, 9)},
        unit: 'm',
        unitPosition: {'start': (0, 10), 'end': (0, 11)},
        variableType: 'scalar',
      ),
      Variable(
        id: 'var_10',
        name: 'Height',
        namePosition: {'start': (1, 0), 'end': (1, 6)},
        valuePosition: {'start': (1, 8), 'end': (1, 10)},
        unit: 'm',
        unitPosition: {'start': (1, 11), 'end': (1, 12)},
        variableType: 'scalar',
      ),
    ],
    points: 6,
    options: ['125.6 m³', '314 m³', '502.4 m³', '628 m³'],
    answer: '125.6 m³',
  ),
];
